# Generated by Django 4.2.23 on 2025-06-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('resource', models.FileField(blank=True, null=True, upload_to='sections/resources/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.module')),
            ],
            options={
                'ordering': ['module', 'title'],
            },
        ),
    ]
